Print message in mkscandir() only on success
This brings the function in line with the others
that only print messages after some action was
performed and aborts the scan should this first
step already fail for some reason.

diff --git a/scan b/scan
--- a/scan
+++ b/scan
@@ -28,9 +28,11 @@ _resolution=150
 	|| _inbox="$HOME"/inbox
 
 mkscandir() {
-	if ! [ -d "${_scandir}" ] ; then
-		printf "${_good}%s${_rset}\n" "Creating scan directory"
-		mkdir -p "${_scandir}"
+	if ! [ -d "${_scandir}" ] && mkdir -p "${_scandir}" ; then
+		printf "${_good}%s${_rset}\n" "Scan directory created"
+	else
+		printf "${_fail}%s${_rset}\n" "Creation of scan directory failed"
+		exit 1
 	fi
 }
 
